dependencies:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'pnpm-lock.yaml'
              - 'package.json'

post:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'src/app/posts/_articles/**/*'

feature:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'src/app/**/*'
              - 'src/components/**/*'

style:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'src/styles/**/*'
              - '*.css'

test:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'tests/**/*'
              - 'playwright.config.ts'

config:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'next.config.ts'
              - 'tsconfig.json'
              - 'biome.json'
              - 'postcss.config.js'

workflows:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '.github/**/*'
