allowBuilds:
  sharp: true
minimumReleaseAgeExclude:
  - lint-staged@17.0.6
  - '@next/env@16.2.9'
  - '@next/mdx@16.2.9'
  - '@next/swc-darwin-arm64@16.2.9'
  - '@next/swc-darwin-x64@16.2.9'
  - '@next/swc-linux-arm64-gnu@16.2.9'
  - '@next/swc-linux-arm64-musl@16.2.9'
  - '@next/swc-linux-x64-gnu@16.2.9'
  - '@next/swc-linux-x64-musl@16.2.9'
  - '@next/swc-win32-arm64-msvc@16.2.9'
  - '@next/swc-win32-x64-msvc@16.2.9'
  - next@16.2.9
  - '@img/sharp-darwin-arm64@0.35.1'
  - '@img/sharp-darwin-x64@0.35.1'
  - '@img/sharp-freebsd-wasm32@0.35.1'
  - '@img/sharp-linux-arm64@0.35.1'
  - '@img/sharp-linux-arm@0.35.1'
  - '@img/sharp-linux-ppc64@0.35.1'
  - '@img/sharp-linux-riscv64@0.35.1'
  - '@img/sharp-linux-s390x@0.35.1'
  - '@img/sharp-linux-x64@0.35.1'
  - '@img/sharp-linuxmusl-arm64@0.35.1'
  - '@img/sharp-linuxmusl-x64@0.35.1'
  - '@img/sharp-wasm32@0.35.1'
  - '@img/sharp-webcontainers-wasm32@0.35.1'
  - '@img/sharp-win32-arm64@0.35.1'
  - '@img/sharp-win32-ia32@0.35.1'
  - '@img/sharp-win32-x64@0.35.1'
  - sharp@0.35.1
